### ISSUE TITLE
[FluxStore Pro][Magento] -  method 'startsWith' was called on null (only with Magento)

### ISSUE THREAD

**Issue by VenyaminBlubinest** [inspireui/support#1622]
1. My issue:
I had Flux Store 1.5.9 working with Magento 2, with just an unknown error. When trying to pay, I tried to call an unknown billing function.

Now I try the 1.6 version of Flux Store, it works perfect with woocomerce (by default) but only throws a blank screen when switching to Magento (with default settings)

Note: I have not generated my own configuration files, I am working with those in the "example \ magento" folder

the error it throws:
"[ERROR: flutter / lib / ui / ui_dart_state.cc (157)] Unhandled Exception: NoSuchMethodError: The method 'startsWith' was called on null."

2. Screenshots issues:
**Error**
![image](https://user-images.githubusercontent.com/51170169/70929497-04c8f380-2012-11ea-9979-c63e9596575a.png)

**Flutter Doctor**
![image](https://user-images.githubusercontent.com/51170169/70929600-33df6500-2012-11ea-8b6e-d2a2c31f3fc5.png)

3. Proof of my purchased:
![image](https://user-images.githubusercontent.com/51170169/70930135-3ee6c500-2013-11ea-9029-5afa27ce0b12.png)

3. Config files (optional)
I have not generated my own configuration files, I am working with those in the "example \ magento" folder

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for checking

**Comment by minhtruong315** [comment]
@VenyaminBlubinest We're having issues our website. I will fix it soon. Then let you know

**Comment by VenyaminBlubinest** [comment]
I have tried version 1.6 with a site (Magento 2) that worked perfectly with version 1.5.9 (except for the payment section) and using the same configuration data generates exactly the same error.

E / flutter (30208): [ERROR: flutter / lib / ui / ui_dart_state.cc (157)] Unhandled Exception: NoSuchMethodError: The method 'startsWith' was called on null.

**Comment by minhtruong315** [comment]
```
const serverConfig = {
  "type": "magento",
  "url": "your website",
  "accessToken": "your access token",
  "blog": "http://listeo.inspireui.com",
};
```
Try this config to fix above issue. thanks
