### ISSUE TITLE
FluxNews 1.4.1. Rate The App

### ISSUE THREAD

**Issue by admincode1** [inspireui/support#4063]
Hello,

Issue 1:
The rate my app on settings page is not working (nothing happens when click "maybe later", "rate" or "no thanks").
I changed kStoreIdentifer, but I'm still having the issue.
Please advises.

Issue 2:
When enabling Dark Theme then close & reopen the app it goes back to default theme, is anyway the app can remember the last settings?

Thanks!

* FluxNews 1.4.1. (latest version).

* Flutter (latest version).

* Simulator: android phone, android emulator.

**Comment by dttrung26** [comment]
Hi @admincode1 , 
please double-check those configurations: 
- rate_my_app plugin is lastest version or not (in pubspec.yaml file). If not, please modify : `rate_my_app: 0.6.1+6`
- in `settings.dart` located at /lib/screens/, inside _rateMyApp initialization, modify those codes as below: 
`
RateMyApp _rateMyApp = RateMyApp(
    minDays: 7,
    minLaunches: 10,
    remindDays: 7,
    remindLaunches: 10,
    googlePlayIdentifier: 'fr.skyost.example', //replace your code here
    appStoreIdentifier: '1491556149',  //replace your code here
  );
`

Hope this helps!

**Comment by admincode1** [comment]
Hi,

I changed the version from rate_my_app: 0.6.0+2 to 0.6.1+6, and added googlePlayIdentifier & appStoreIdentifier.
"Rate" & "No Thanks" works fine but when I press "Maybe Later" nothing happens.

How about the other plugins should I update all? Any kb for that?

Thanks dttrung26.

**Comment by admincode1** [comment]
I also having a problem with the splash screen, it start with blue and black (animated part) then gets to my splash screen with no animation. 

Any advise?

**Comment by admincode1** [comment]
Build failed in xcode.

![image](https://user-images.githubusercontent.com/67590385/86683451-3df69e80-c00a-11ea-89b6-b3a861b678af.png)
![image](https://user-images.githubusercontent.com/67590385/86683485-451dac80-c00a-11ea-98cf-2b0009ded0ce.png)

[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en)
    • Flutter version 1.17.5 at /Users/myname/Dev/flutter
    • Framework revision 8af6b2f038 (6 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/user176947/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • iPhone 8 Plus • A847113A-AF5A-4AFD-BEC9-227F5835A9B5 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!

**Comment by dttrung26** [comment]
Hi @admincode1 , 
as I tested so far, your splash screen config still works fine with FluxNews 1.4.1. 
Could you show me your error log on both cases: when you click on "Later" on RateMyApp, and when you navigate to SplashScreen? And please attach your _rateMyApp initialization on settings.dart. 
Best!

**Comment by admincode1** [comment]
Hello Doan,

(1) Splash Screen:

I tested the splash screen on my app and fresh installation of FluxNews
1.4.1 and both with same result, here is the error I received:

    #4      _AnimatedSplashState.build.<anonymous closure>
(package:fstore/widgets/common/animated_splash.dart:75:23)

(2) Rate My App:

From settings.dart:

class SettingScreenState extends State<SettingScreen>
    with TickerProviderStateMixin, WidgetsBindingObserver {
  final bannerHigh = 200.0;
  bool enabledNotification = true;
  bool isAbleToPostManagement = false;
  RateMyApp _rateMyApp = RateMyApp(
    minDays: 7,
    minLaunches: 10,
    remindDays: 7,
    remindLaunches: 10,
    googlePlayIdentifier: 'com.xxxxx.xxx', //replace your code here
    appStoreIdentifier: 'xxxxxxxxxxx',  //replace your code here
  );

Error logs when I press "Maybe Later":

2020-07-07 06:16:36.620 23707-23800/com.xxxxx.xxx E/flutter:
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception:
NoSuchMethodError: The method '-' was called on null.
    Receiver: null
    Tried calling: -(10)
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
    #1      MinimumAppLaunchesCondition.onEventOccurred
(package:rate_my_app/src/conditions.dart:131:16)
    #2      RateMyApp.callEvent.<anonymous closure>
(package:rate_my_app/src/core.dart:186:73)
    #3      List.forEach (dart:core-patch/growable_array.dart:282:8)
    #4      RateMyApp.callEvent (package:rate_my_app/src/core.dart:186:16)
    #5      RateMyAppLaterButton.onButtonClicked
(package:rate_my_app/src/dialogs.dart:321:21)
    #6      _RateMyAppDialogButton.build.<anonymous closure>
(package:rate_my_app/src/dialogs.dart:267:17)
    #7      _InkResponseState._handleTap
(package:flutter/src/material/ink_well.dart:779:19)
    #8      _InkResponseState.build.<anonymous closure>
(package:flutter/src/material/ink_well.dart:862:36)
    #9      GestureRecognizer.invokeCallback
(package:flutter/src/gestures/recognizer.dart:182:24)
    #10     TapGestureRecognizer.handleTapUp
(package:flutter/src/gestures/tap.dart:504:11)
    #11     BaseTapGestureRecognizer._checkUp
(package:flutter/src/gestures/tap.dart:282:5)
    #12     BaseTapGestureRecognizer.handlePrimaryPointer
(package:flutter/src/gestures/tap.dart:217:7)
    #13     PrimaryPointerGestureRecognizer.handleEvent
(package:flutter/src/gestures/recognizer.dart:475:9)
    #14     PointerRouter._dispatch
(package:flutter/src/gestures/pointer_router.dart:76:12)
    #15     PointerRouter._dispatchEventToRoutes.<anonymous closure>
(package:flutter/src/gestures/pointer_router.dart:122:9)
    #16     _LinkedHashMapMixin.forEach
(dart:collection-patch/compact_hash.dart:379:8)
    #17     PointerRouter._dispatchEventToRoutes
(package:flutter/src/gestures/pointer_router.dart:120:18)
    #18     PointerRouter.route
(package:flutter/src/gestures/pointer_router.dart:106:7)
    #19     GestureBinding.handleEvent
(package:flutter/src/gestures/binding.dart:218:19)
    #20     GestureBinding.dispatchEvent
(package:flutter/src/gestures/binding.dart:198:22)
    #21     GestureBinding._handlePointerEvent
(package:flutter/src/gestures/binding.dart:156:7)
    #22     GestureBinding._flushPointerEventQueue
(package:flutter/src/gestures/binding.dart:102:7)
    #23     GestureBinding._handlePointerDataPacket
(package:flutter/src/gestures/binding.dart:86:7)
    #24     _rootRunUnary (dart:async/zone.dart:1196:13)
    #25     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
    #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
    #27     _invoke1 (dart:ui/hooks.dart:275:10)
    #28     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)

**Comment by admincode1** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/67590385/86702332-87031e80-c01b-11ea-9ca2-09e0a7726a2d.gif)

**Comment by dttrung26** [comment]
Hi @admincode1 , 
kindly contact me via skype: dttrung.ityu@gmail.com. I would like to run TeamViewer because the information given is not enough.

**Comment by dttrung26** [comment]
Support via skype
